name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest commit (uses latest version of actions/checkout)
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 3: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 4: Grant execute permissions to Gradle Wrapper
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # Step 5: Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Step 6: Debug APK Directory
      - name: Debug APK Directory
        run: ls -R app/build/outputs/apk/release/

      # Step 7: Upload APK file as artifact
      - name: Upload APK file
        uses: actions/upload-artifact@v4
        with:
          name: CNote-APK
          path: app/build/outputs/apk/release/*.apk
