name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout latest commit
      - name: Checkout Code
        uses: actions/checkout@v4

      # Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Decode Keystore from Base64
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.CN_NOTE_STORE_FILE }}
        run: |
          echo "$ENCODED_KEYSTORE" | base64 --decode > app/cnote-keystore.jks
          ls -l app/  # Debug to check if file exists

      # Inject Secrets into gradle.properties
      - name: Inject Signing Configs
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "CN_NOTE_STORE_FILE=app/cnote-keystore.jks" >> gradle.properties
          echo "CN_NOTE_STORE_PASSWORD=${{ secrets.CN_NOTE_STORE_PASSWORD }}" >> gradle.properties
          echo "CN_NOTE_KEY_ALIAS=${{ secrets.CN_NOTE_KEY_ALIAS }}" >> gradle.properties
          echo "CN_NOTE_KEY_PASSWORD=${{ secrets.CN_NOTE_KEY_PASSWORD }}" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "kotlin.code.style=official" >> gradle.properties

      # Grant execute permission for Gradlew
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Debug APK Directory
      - name: Debug APK Directory
        run: ls -R app/build/outputs/apk/release/

      # Upload APK file
      - name: Upload APK file
        uses: actions/upload-artifact@v4
        with:
          name: CNote-APK
          path: app/build/outputs/apk/release/*.apk
